name: "SocialGouv scanners Action"
description: "Run a bunch of scans on a given URL"

inputs:
  url:
    description: "URL to scan"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install
      shell: bash
      run: |
        yarn
        mkdir -p scans || true

    - name: SSL Labs scan
      shell: bash
      run: |
        SCAN_OUTPUT=scans/ssl.json
        node src/ssl/scan.js ${{ inputs.url }} > $SCAN_OUTPUT

    - name: Mozilla HTTP scan
      shell: bash
      run: |
        SCAN_OUTPUT=scans/ssl.json
        node src/http/scan.js ${{ inputs.url }} > $SCAN_OUTPUT

    - name: Third parties scan
      shell: bash
      run: |
        SCAN_OUTPUT=scans/ssl.json
        node src/thirdparties/scan.js ${{ inputs.url }} > $SCAN_OUTPUT
