name: "Nuclei Action"
description: "Nuclei is a fast and customisable vulnerability scanner based on simple YAML based DSL"

inputs:
  urls:
    description: "List of urls to run templates"
    required: true
    default: "urls.txt"
  output:
    description: "File to save output result"
    required: false
    default: "nuclei.log"
  user-agent:
    description: "Set a User-Agent header"
    required: false
    default: "Nuclei - Open-source project (github.com/projectdiscovery/nuclei)"

runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/nuclei ] && GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        nuclei -ut -ud /app/nuclei-templates

        echo "-----"
        echo ${{ inputs.urls }}
        echo "-----"
        cat ${{ inputs.urls }}
        echo "-----"
        ls /app/nuclei-templates
        echo "-----"

        nuclei \
          -l ${{ inputs.urls }} \
          -t /app/nuclei-templates \
          -o ${{ inputs.output }} \
          -H "User-Agent: ${{ inputs.user-agent }}" \
          -json \
          -include-rr \
          \
      shell: bash
