on:
  #  workflow_dispatch:
  # inputs:
  #   tags:
  #     description: "Test tags"
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 6 */7 * *"
name: Scans
jobs:
  scans:
    runs-on: ubuntu-latest
    name: Scan
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: /home/runner/go/bin/nuclei
          key: ${{ runner.os }}-${{ hashFiles('/home/runner/go/bin/nuclei') }}

      # - uses: projectdiscovery/nuclei-action@main
      #   with:
      #     urls: "urls.txt"
      #     templates: "nuclei-templates"
      #     output: "nuclei.log"

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: nuclei.log
      #     path: nuclei.log
      # - name: Checkout
      #   uses: actions/checkout@v2
      #   # with:
      #   #   ref: master
      # - name: Install
      #   run: |
      #     yarn
      #     mkdir -p results/$GITHUB_RUN_ID
      # # - name: ssl-scan
      # #   run: |
      # #     SCAN_OUTPUT=results/$GITHUB_RUN_ID/ssl.json
      # #     node src/ssl/scan.js > $SCAN_OUTPUT
      # #  node src/ssl/toMarkdown.js $SCAN_OUTPUT > README.md
      # - name: trackers-scan
      #   run: |
      #     SCAN_OUTPUT=results/$GITHUB_RUN_ID/trackers.json
      #     node src/thirdparties/scan.js > $SCAN_OUTPUT
      #     ls
      # #   #   node src/toMarkdown.js $SCAN_OUTPUT > README.md
      # - uses: projectdiscovery/nuclei-action@main
      #   with:
      #     urls: "urls.txt"
      #     templates: "nuclei-templates"
      #     output: "nuclei.log"
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: "urls.txt"
          uploadArtifacts: true
          temporaryPublicStorage: false

      - name: cleanup
        run: |
          ls
      # - name: Audit URLs using Lighthouse
      #   uses: treosh/lighthouse-ci-action@v7
      #   with:
      #     urls: |
      #       https://www.free.fr
      #     uploadArtifacts: true
      #     temporaryPublicStorage: false
      # - name: OWASP ZAP Scan
      #   uses: zaproxy/action-baseline@v0.4.0
      #   with:
      #     #  token: "${{ secrets.GITHUB_TOKEN }}"
      #     docker_name: "owasp/zap2docker-stable"
      #     target: https://www.free.fr
      #     cmd_options: "-a"
