on:
  #  workflow_dispatch:
  # inputs:
  #   tags:
  #     description: "Test tags"
  push:
    branches:
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 6 */7 * *"
name: Scans
jobs:
  scans:
    runs-on: ubuntu-latest
    name: Scan
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          yarn
          mkdir -p results/$GITHUB_RUN_ID

      ######@
      # - name: ssl-scan
      #   run: |
      #     SCAN_OUTPUT=results/$GITHUB_RUN_ID/ssl.json
      #     node src/ssl/scan.js > $SCAN_OUTPUT
      #     ls results/$GITHUB_RUN_ID

      # - name: trackers-scan
      #   run: |
      #     SCAN_OUTPUT=results/$GITHUB_RUN_ID/trackers.json
      #     node src/thirdparties/scan.js > $SCAN_OUTPUT
      #     ls results/$GITHUB_RUN_ID

      # - uses: "./.github/actions/nuclei"
      #   with:
      #     urls: "urls.txt"
      #     output: "nuclei.log"
      ######@

      - name: "Parse urls for lighthouse"
        id: "parse-urls"
        run: echo "::set-output name=urls::$(cat urls.txt)"
        shell: bash

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: ${{ join(steps.parse-urls.outputs.urls) }}
          uploadArtifacts: true
          temporaryPublicStorage: false

      - name: cleanup
        run: |
          ls
          ls results/$GITHUB_RUN_ID
      # - name: Audit URLs using Lighthouse
      #   uses: treosh/lighthouse-ci-action@v7
      #   with:
      #     urls: |
      #       https://www.free.fr
      #     uploadArtifacts: true
      #     temporaryPublicStorage: false
      # - name: OWASP ZAP Scan
      #   uses: zaproxy/action-baseline@v0.4.0
      #   with:
      #     #  token: "${{ secrets.GITHUB_TOKEN }}"
      #     docker_name: "owasp/zap2docker-stable"
      #     target: https://www.free.fr
      #     cmd_options: "-a"
